name: Build Windows EXE

on:
  push:
    branches: [ main ]   # Run every time you push to main
  workflow_dispatch:      # Allow manual runs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # can be 3.11/3.12/3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE (no console)
        run: |
          pyinstaller --onefile --windowed ^
            --icon windows-updater.ico ^
            App-Updater.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-App-Updater
          path: dist/App-Updater.exe
