name: Release Windows EXE

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build EXE (no console)
        run: pyinstaller --noconfirm --onefile --windowed --icon "windows-updater.ico" App-Updater.py
        # If your entry is .pyw, change to App-Updater.pyw

      - name: Verify and rename EXE with tag
        run: |
          if (!(Test-Path "dist\App-Updater.exe")) {
            Write-Error "Build failed: dist\App-Updater.exe not found"
          }
          $tag = "${{ github.ref_name }}"
          Rename-Item "dist\App-Updater.exe" "dist\Windows-App-Updater-$tag.exe"

      - name: Create GitHub Release and upload EXE
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/Windows-App-Updater-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
